# ClanPlugin Configuration

# General settings
settings:
  max_clan_name_length: 16
  max_clan_tag_length: 5
  default_chat_color: GOLD

# Territory system settings
territory:
  enabled: true
  max_base_claims: 10
  claim_per_member: 2
  officer_bonus_claims: 3
  alliance_bonus_claims: 1
  
  # Flag settings
  flags:
    max_tier: 3
    upgrade_cost: 100
    
  # Protection levels (influence thresholds)
  protection:
    core: 75
    secure: 50
    contested: 25
    frontier: 1
    
  # Map settings
  map:
    default_radius: 8
    max_radius: 15

# Economy system settings
economy:
  enabled: true
  starting_balance: 0
  default_tax_rate: 0.05
  tax_collection_cooldown_hours: 24
  
  # Territory costs
  territory_costs:
    claim_cost: 50
    daily_upkeep: 5
    flag_place_cost: 25

# War system settings
wars:
  enabled: true
  default_duration_days: 7
  min_members_for_war: 3
  cooldown_between_wars_days: 2
  
  # Victory rewards
  rewards:
    victory_bonus: 500
    kill_bonus: 10
    
  # Reputation effects
  reputation:
    win_gain: 50
    loss_loss: 25
    surrender_loss: 40

# Chat settings
chat:
  clan_tag_format: "[%tag%] "
  alliance_color: BLUE
  enemy_color: RED
  neutral_color: GRAY

# Colors available for clans
colors:
  - RED
  - BLUE
  - GREEN
  - YELLOW
  - LIGHT_PURPLE
  - AQUA
  - GOLD
  - BLACK
  - WHITE
  
# Progression system settings
progression:
  enabled: true
  
  # Experience sources
  experience:
    territory_claim: 50
    war_victory: 500
    war_kill: 10
    alliance_formed: 100
    member_joined: 50
    
  # Level definitions
  levels:
    1:
      exp_required: 0
      benefits:
        max_members: 10
        max_territory: 5
    2:
      exp_required: 1000
      benefits:
        max_members: 15
        max_territory: 10
        income_bonus: 5
    3:
      exp_required: 3000
      benefits:
        max_members: 20
        max_territory: 15
        income_bonus: 10
        influence_bonus: 5
    4:
      exp_required: 7000
      benefits:
        max_members: 25
        max_territory: 20
        income_bonus: 15
        influence_bonus: 10
        armor_bonus: 1
    5:
      exp_required: 15000
      benefits:
        max_members: 30
        max_territory: 25
        income_bonus: 20
        influence_bonus: 15
        armor_bonus: 2
        strength_bonus: 1

# Achievement system settings
achievements:
  enabled: true
  
  # Achievement definitions
  first_clan:
    name: "Founding Father"
    description: "Create your first clan"
    category: GENERAL
    difficulty: EASY
    exp_reward: 100
    rep_reward: 10
    
  recruit_members:
    name: "Recruitment Drive"
    description: "Have at least 5 members in your clan"
    category: GENERAL
    difficulty: EASY
    exp_reward: 200
    rep_reward: 20
    
  clan_master:
    name: "Clan Master"
    description: "Reach level 5 with your clan"
    category: PROGRESSION
    difficulty: HARD
    exp_reward: 1000
    rep_reward: 100
    
  # More achievements are defined in AchievementManager
  
# Skill system settings
skills:
  enabled: true
  
  # Skill point sources
  skill_points:
    level_up: 5
    achievement: 1
    war_victory: 3
    
  # Default skill definitions are in SkillManager
  
# Reputation system settings
reputation:
  enabled: true
  
  # Reputation sources
  sources:
    territory_claim: 5
    war_victory: 50
    war_loss: -25
    alliance_formed: 10
    enemy_declared: -5
    
  # Reputation effects
  effects:
    territory_bonus:
      legendary: 5
      renowned: 4
      distinguished: 3
      respected: 2
      recognized: 1
    
    # More effects defined in ReputationManager

# Visual identity settings
visual_identity:
  # Colored armor settings
  armor:
    enabled: true
    min_clan_level: 2  # Min clan level to enable colored armor
    provide_armor: false  # Whether to provide armor if player doesn't have it
    prevent_armor_removal: false  # Whether players can remove clan armor
    prevent_armor_drops: true  # Whether clan armor drops on death
    clan_color_armor_pieces: "ALL"  # Which pieces to color: ALL, HELMET, CHESTPLATE, LEGGINGS, BOOTS
  
  # Nametag settings
  nametags:
    enabled: true
    display_clan_tag: true
    show_in_tab_list: true
    clan_friendly_fire: true  # Whether clan members can damage each other
    can_see_friendly_invisibles: true  # Whether clan members can see invisible teammates